steps:
  # Deploy to Cloud Run using source-based deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--source=.'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--timeout=3600'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--concurrency=1'
      - '--port=8080'
      # Non-sensitive environment variables
      - '--set-env-vars=NODE_ENV=production'
      - '--set-env-vars=PORT=8080'
      - '--set-env-vars=channel_group_key=channel_id'
      - '--set-env-vars=slack_prefix=${_SLACK_PREFIX}'
      - '--set-env-vars=service_name=${_SERVICE_NAME}'
      - '--set-env-vars=gcs_bucket=${_GCS_BUCKET}'
      - '--set-env-vars=gcs_path=${_GCS_PATH}'
      - '--set-env-vars=company_domain=${_COMPANY_DOMAIN}'
      # Sensitive values from Secret Manager
      - '--set-secrets=slack_bot_token=slack_bot_token:latest'
      - '--set-secrets=slack_user_token=slack_user_token:latest'
      - '--set-secrets=mixpanel_token=mixpanel_token:latest'
      - '--set-secrets=mixpanel_secret=mixpanel_secret:latest'

# Substitution variables
substitutions:
  _SERVICE_NAME: 'slack-mixpanel-analytics'
  _REGION: 'us-central1'
  _SLACK_PREFIX: 'https://mixpanel.slack.com'
  _GCS_BUCKET: 'mixpanel-slack-analytics'
  _GCS_PATH: 'gs://mixpanel-slack-analytics/data'
  _COMPANY_DOMAIN: 'mixpanel.com'

options:
  logging: CLOUD_LOGGING_ONLY